<a href="https://colab.research.google.com/github/joohoshin/TensorflowAI/blob/main/25_2_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor의 기본 구조를 알아봅시다

https://www.tensorflow.org/guide/tensor

전체적으로는 Numpy와 유사

In [37]:
import tensorflow as tf

In [38]:
# 변수에 값과 배열을 넣어봅시다
a = tf.constant(3)
a

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [40]:
# numpy 변환
b=a.numpy()

In [41]:
type(b)

numpy.int32

사칙연산 및 행렬곱 등도 쉽게 가능함

In [42]:
arr = tf.constant([[1,2], [3,4]])

In [ ]:
arr

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [43]:
arr+3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 5],
       [6, 7]], dtype=int32)>

In [44]:
arr*3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  6],
       [ 9, 12]], dtype=int32)>

In [45]:
arr2 = tf.constant([[3,4], [5,6]])

In [46]:
arr+arr2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4,  6],
       [ 8, 10]], dtype=int32)>

In [47]:
arr*arr2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 3,  8],
       [15, 24]], dtype=int32)>

In [48]:
arr@arr2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 16],
       [29, 36]], dtype=int32)>

In [49]:
tf.argmax(arr)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 1])>

Indexing도 Numpy와 동일함

In [50]:
arr3 = tf.constant([1,2,3,4,5])

In [51]:
arr3[:3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [52]:
arr3[:3].numpy()

array([1, 2, 3], dtype=int32)

In [53]:
arr4 = tf.constant([[1,2,3,4,5],[2,3,4,5,6]])

In [54]:
arr4

<tf.Tensor: shape=(2, 5), dtype=int32, numpy=
array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]], dtype=int32)>

In [55]:
arr4[0].numpy()

array([1, 2, 3, 4, 5], dtype=int32)

In [56]:
tf.reshape(arr4, [5,2])

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [58]:
arr3.dtype

tf.int32

In [59]:
arr4 = tf.cast(arr4, dtype = tf.float16)

In [62]:
arr4.dtype

tf.float16

tf.variable을 통해 변수를 만들수도 있습니다.

https://www.tensorflow.org/guide/variable

In [63]:
a = tf.Variable([2.0, 3.0])

In [64]:
a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [65]:
a.assign_add([1,2])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=float32, numpy=array([3., 5.], dtype=float32)>

In [66]:
a

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([3., 5.], dtype=float32)>

tensor는 정수와 실수형이 연산되지 않습니다.
 
tf.cast()를 통해서 타입을 맞춰주어야 합니다. 

In [67]:
n1 =tf.constant(10)
n2 = tf.constant(5.)

In [68]:
n1+n2

InvalidArgumentError: ignored

In [69]:
n1 = tf.cast(n1, tf.float32)

In [70]:
n1+n2

<tf.Tensor: shape=(), dtype=float32, numpy=15.0>