<a href="https://colab.research.google.com/github/joohoshin/TensorflowAI/blob/main/25_3_Subclassing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Keras의 Layer 구조를 직접 정의할 수도 있습니다. 

https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer

파이썬의 클래스에 대해 알아야 합니다

https://wikidocs.net/28

간단한 버전을 만들어봅시다. 

실제 사용시에는 keras layer의 위의 링크를 참조하여 build, get_config도 구현하는 것이 좋습니다.

In [8]:

from tensorflow import keras

class Linear(keras.layers.Layer):
    def __init__(self, units=32, input_dim=32):
        super().__init__()
        w_init = tf.random_normal_initializer()
        self.w = tf.Variable(
            initial_value=w_init(shape=(input_dim, units), dtype="float32"),
            trainable=True,
        )
        b_init = tf.zeros_initializer()
        self.b = tf.Variable(
            initial_value=b_init(shape=(units,), dtype="float32"), trainable=True
        )

    def call(self, inputs):
        return tf.matmul(inputs, self.w) + self.b

random_normal_initializer 사용 확인

In [9]:
import tensorflow as tf
w_init = tf.random_normal_initializer()

In [10]:
initial_value=w_init(shape=(4, 2), dtype="float32")

In [11]:
initial_value

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ 0.05380461, -0.04474404],
       [-0.12714718, -0.02094029],
       [-0.09268957,  0.01545976],
       [-0.00834726,  0.02165216]], dtype=float32)>

In [12]:
dense_simple = Linear(4,2)

In [13]:
in_ = tf.constant([1.,2.])

In [14]:
in_

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [15]:
dense_simple([in_])

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[ 0.01617678, -0.04343504,  0.11032546,  0.02377586]],
      dtype=float32)>

Model에 대해서도 만들 수 있습니다

https://www.tensorflow.org/api_docs/python/tf/keras/Model